### ISSUE TITLE
Class 'Facebook\FacebookSession' not found "

### ISSUE THREAD

**Issue by eduhakim** [darkwhispering/facebook-sdk-v4-codeigniter#4]
hii darkwhispering ..
I try your library but I find trouble, may be I dont understand how to instalation your library in point no 3 that "In CodeIgniter /application/config/config.php, configure the Session Variables." or point no 5 ..
I have setting /application/config/facebook.php with my facebook app id and facebook app secret ..

I found message eror report like this " Message: Class 'Facebook\FacebookSession' not found "
![eror fb](https://cloud.githubusercontent.com/assets/13493474/8889847/75da2c86-3315-11e5-9339-3d614b3184e8.PNG)
If you know this solution, please explain to me ..
Thanks

**Comment by darkwhispering** [comment]
Hi @eduhakim, sry for this late reply.

For point on 3, you need to activate and configure the CI session library, using one of the available drivers. Read more about it in the [CI Documentation](http://www.codeigniter.com/userguide3/libraries/sessions.html#session-drivers)

For point no 5. To download and install the Facebook SDK you need to user Composer, a dependency manager for PHP. Details on how to user Composer can be found on there [website](https://getcomposer.org/doc/00-intro.md)

I'm guessing you see the error because you have not installed the Facebook SDK using Composer.

**Comment by bsimser** [comment]
This also might be caused by the update to the SDK. If you have it installed you have to make sure you have 4.x installed and not 5.x. The 5.x version no longer has a FacebookSession class and running your script will fail on this line (it did for me when I realized the SDK updated). Also don't be fooled by the SDK directory name (facebook-sdk-v4). They left the folder/package name intact but updated the version.

**Comment by tarunmangukiya** [comment]
In index.php file of CodeIgniter...

Add the line
`include_once './vendor/autoload.php';`
just before the `require_once BASEPATH.'core/CodeIgniter.php';` line.

It's not loading the autoload.php by default.

**Comment by darkwhispering** [comment]
@tarunmangukiya If you use CodeIgniter 3, you don't need to manually include the autoload file. [CodeIgniter 3 has built in support for Composer](http://www.codeigniter.com/userguide3/general/autoloader.html?highlight=composer).

However, if you use CodeIgniter 2 or below (which this library do not support), you need to manually add the autoload file as you commented.

**Comment by tarunmangukiya** [comment]
True... Recently I came to know about that.


Thank you,Tarun MangukiyaCo-founder | Remarkin - Learn to Code | https://remarkin.comMicrosoft Student Partner | Microsoft

Date: Tue, 6 Oct 2015 10:16:55 -0700

**Comment by Nbasu** [comment]
Hello everyone, 

I'm unable to load the library of FB... Same error message but not the session actually it's showing unable to load class Facebook /Facebook class 

Line no 67 in library file of Facebook 
I configure the config file and session also 
Please help me 

Thank you
